"""Last transaction

Revision ID: 49dedf0f4e6b
Revises: 8a5f0be630ee
Create Date: 2023-01-11 13:40:02.674674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49dedf0f4e6b'
down_revision = '8a5f0be630ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_transaction', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compte', schema=None) as batch_op:
        batch_op.drop_column('last_transaction')

    # ### end Alembic commands ###
